# Generated by Django 5.2.2 on 2025-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=100)),
                ('almacenamiento', models.CharField(max_length=100)),
                ('monitor', models.CharField(max_length=100)),
                ('raton', models.CharField(max_length=100)),
                ('sistema_operativo', models.CharField(max_length=100)),
            ],
        ),
    ]
