# Generated by Django 5.2.2 on 2025-06-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En mantenimiento'), ('no_disponible', 'No disponible')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='almacenamiento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='memoria_ram',
            field=models.CharField(max_length=50),
        ),
    ]
